FROM apache/airflow:2.10.3

RUN pip install --no-cache-dir \
    python-json-logger \
    tenacity \
    pymongo \
    python-dotenv \
    requests \
    pandas \
    python-dateutil

ENV PATH=/home/airflow/.local/bin:$PATH

USER airflow